// Authorization action types
export const INPUT_CHANGE = 'input_change';
export const GET_CSRF = 'get_csrf';
export const GET_CSRF_SUCCESS = 'get_csrf_success';
export const SIGNIN = 'signin';
export const SIGNIN_FAIL = 'signin_fail';
export const SIGNIN_SUCCESS = 'signin_success';
export const SIGNUP = 'signup';
export const CLEAR_ERROR_MESSAGE = 'clear_error_message';
export const RESOLVE_AUTH = 'resolve_auth';
export const HAS_BIO_SCANNER = 'has_bio_scanner';
export const IS_BIO_AUTH_ACTIVE = 'is_bio_auth_active';
// Catalog fetch action types
export const FETCH_CATALOG = 'fetch_catalog';
export const FETCH_SUCCESS = 'fetch_success';
export const FETCH_FAIL = 'fetch_fail';
// Edit profile action types
export const GET_PROFILE_INFO = 'get_profile_info';
export const GET_PROFILE_INFO_SUCCESS = 'get_profile_info_success';
export const GET_PROFILE_INFO_FAIL = 'get_profile_info_fail';
export const PROFILE_INPUT_CHANGE = 'profile_input_change';
export const EDIT = 'edit';
export const EDIT_SUCCESS = 'edit_success';
export const EDIT_FAIL = 'edis_fail';
export const GET_PROFILE_CSRF = 'get_profile_csrf';
// Garden action types
export const GARDEN_INPUT_CHANGE = 'garnden_input_change';
export const GET_GARDENS = 'get_gardens';
export const ADD_BUTTON = 'add_button';
export const CREATE_GARDEN = 'create_garden';
export const CLEAR_STATE = 'clear_state';
export const DELETE_GARDEN = 'delete_garden';
export const OPEN_ITEM = 'open_item';
export const BUTTON_ACTION = 'button_action';
export const EDIT_GARDEN = 'edit_garden';
export const UPDATE_GARDEN = 'update_garden';
